#!/usr/bin/env python2

import requests

from requests.packages.urllib3.exceptions import (SNIMissingWarning,
    InsecurePlatformWarning, InsecureRequestWarning)
from gitlabissues import GitLabIssues

requests.packages.urllib3.disable_warnings(SNIMissingWarning)
requests.packages.urllib3.disable_warnings(InsecurePlatformWarning)
requests.packages.urllib3.disable_warnings(InsecureRequestWarning)


if __name__ == '__main__':
    gi = GitLabIssues()
    gi.list_issues()
