#!/usr/bin/env python2

import argparse
import colorama
import requests

from gitlabissues import GitLabIssues
from requests.packages.urllib3.exceptions import (SNIMissingWarning,
        InsecurePlatformWarning, InsecureRequestWarning)

requests.packages.urllib3.disable_warnings(SNIMissingWarning)
requests.packages.urllib3.disable_warnings(InsecurePlatformWarning)
requests.packages.urllib3.disable_warnings(InsecureRequestWarning)

def parse_args():
    parser = argparse.ArgumentParser(description='Manages issues')

    args = parser.parse_args()
    return args


if __name__ == '__main__':
    colorama.init()

    parse_args()

    gi = GitLabIssues()
    gi.list_issues()
